export const DATA = [
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Mario',
    universe: 'Mario',
    price: '273',
    popular: true,
    rate: 5,
    downloads: '52778',
    description:
      "Mario (マリオ, Mario) is a playable character in Super Smash Bros. Ultimate. He was suggested to appear in the then unnamed Ultimate in its first teaser trailer at the end of the March 8th, 2018 Nintendo Direct, and officially announced in Ultimate's E3 2018 trailer on June 12th, 2018 alongside the rest of the returning roster. Mario is classified as Fighter #01, the first fighter number of the SSB veterans and fighters as a whole. As in Smash 4, Charles Martinet's portrayal of Mario from Brawl was repurposed for Ultimate.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/1.png',
  },
  {
    objectID: '537f6063-f9c6-4a5c-bf07-b8254b4e1a9d',
    name: 'Luigi',
    universe: 'Mario',
    price: '895',
    popular: false,
    rate: 3,
    downloads: '49113',
    description:
      "Luigi (ルイージ, Luigi) is a playable character in Super Smash Bros. Ultimate. He was confirmed alongside Yoshi and the rest of the returning roster on June 12th, 2018 during E3 2018, being the last two veterans to be revealed for the game. Like in games prior to Super Smash Bros. 4, he is unlockable, instead of being available from the start. Luigi is classified as Fighter #09.  As in Smash 4, Charles Martinet's portrayal of Luigi from Super Smash Bros. Brawl was repurposed for Ultimate.",
    created_at: 'Sat Nov 06 2021 23:48:01 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/2.png',
  },
  {
    objectID: '791c0429-8a81-4589-9774-dee78cdacd28',
    name: 'Peach',
    universe: 'Mario',
    price: '792',
    popular: true,
    rate: 3,
    downloads: '39018',
    description:
      "Peach (ピーチ, Peach) is a playable character in Super Smash Bros. Ultimate. Peach was revealed for the game along with the rest of the veterans on June 12th, 2018. However, unlike previous Smash Bros. games since Melee (her first playable appearance in the Super Smash Bros. series), Peach is now an unlockable character rather than being available from the start. Peach is classified as Fighter #13, the first fighter number of the Melee veterans.  As in SSB4, Samantha Kelly's portrayal of Peach from Brawl was repurposed for Ultimate.",
    created_at: 'Fri Jun 10 2022 05:09:36 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/3.png',
  },
  {
    objectID: 'a48b9374-02ec-4db3-a6c3-2c1c22fa6d3e',
    name: 'Bowser',
    universe: 'Mario',
    price: '640',
    popular: true,
    rate: 1,
    downloads: '29673',
    description:
      "Bowser (クッパ, Koopa) is a playable character in Super Smash Bros. Ultimate. He was suggested to appear in the then unnamed Ultimate in its first teaser trailer at the end of the March 8th, 2018 Nintendo Direct, and officially announced in Ultimate's E3 2018 trailer As opposed to being a starter character like in previous Smash games, Bowser is now an unlockable character. Bowser is classified as Fighter #14.  Bowser retains the realistic roar voice clips that he had in Super Smash Bros. 4, along with additional new, less bestial-sounding clips, instead of using his voice actor, Kenny James.",
    created_at: 'Fri Sep 23 2022 22:07:57 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/4.png',
  },
  {
    objectID: 'c22e4bfd-0d4f-4103-bf60-69a8c98e9238',
    name: 'Dr. Mario',
    universe: 'Mario',
    price: '800',
    popular: false,
    rate: 5,
    downloads: '11320',
    description:
      "Dr. Mario (ドクターマリオ, Doctor Mario) is a playable character in Super Smash Bros. Ultimate. He was officially revealed on June 12th, 2018 alongside R.O.B., Duck Hunt, and the rest of the returning roster. While Dr. Mario remains a full clone of Mario, he is not classified as an Echo Fighter. As such, Dr. Mario is classified as Fighter #18. As in SSB4, Charles Martinet's portrayal of Mario from Brawl was repurposed for Dr. Mario in Ultimate.",
    created_at: 'Mon Jun 20 2022 23:38:26 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/5.png',
  },
  {
    objectID: '45380ec4-37f6-41c7-8db8-b4607c215db5',
    name: 'Rosalina & Luma',
    universe: 'Mario',
    price: '444',
    popular: true,
    rate: 4,
    downloads: '15313',
    description: 'Ayla',
    created_at: 'Sat Mar 12 2022 08:26:32 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/6.png',
  },
  {
    objectID: '829944a0-65bb-4c91-a549-8a44f503e4e8',
    name: 'Bowser Jr.',
    universe: 'Mario',
    price: '581',
    popular: false,
    rate: 5,
    downloads: '45924',
    description:
      "Bowser Jr. (クッパJr., Koopa Jr.) is a playable character in Super Smash Bros. Ultimate. He was revealed for the game along with the rest of the veterans on June 12th, 2018. He returns with his Junior Clown Car, and the Koopalings return as alternate characters alongside him. Bowser Jr. is classified as Fighter #58. As in Smash 4, Caety Sagoian's portrayals of Bowser Jr. from various Mario spin-off games, along with Lani Minella's portrayals of Larry, Morton, Wendy, and Lemmy, Mike Vaughn’s portrayals of Iggy and Ludwig, and Dan Falcone's portrayal of Roy from the New Super Mario Bros. games were repurposed for Ultimate, in place of the Koopalings' respective voice actors (except Roy) from Mario Kart 8 onward.",
    created_at: 'Thu Apr 07 2022 07:35:16 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/7.png',
  },
  {
    objectID: '05366f78-f910-4f64-a19a-758cbf6ab814',
    name: 'Yoshi',
    universe: 'Mario',
    price: '341',
    popular: true,
    rate: 5,
    downloads: '40379',
    description:
      "Yoshi (ヨッシー, Yoshi) is a playable character in Super Smash Bros. Ultimate. He was revealed for the game along with the rest of the veterans on June 12th, 2018; he was the last veteran to be confirmed along with Luigi, appearing at the very end of the trailer. Yoshi is classified as Fighter #05. As in all previous Smash Bros. games, Kazumi Totaka's portrayal of Yoshi from Yoshi's Story and various games of the Mario series was repurposed for Ultimate",
    created_at: 'Sun Jul 10 2022 21:34:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/8.png',
  },
  {
    objectID: '6bdcf412-22cb-4424-8659-246d7da1c659',
    name: 'Donkey Kong',
    universe: 'Donkey Kong',
    price: '110',
    popular: true,
    rate: 4,
    downloads: '30143',
    description:
      'Donkey Kong (ドンキーコング, Donkey Kong) is a playable character in Super Smash Bros. Ultimate. He was confirmed on June 12th, 2018. Donkey Kong is classified as Fighter #02. Donkey Kong retains his realistic gorilla grunts and roars from Super Smash Bros. 4, instead of using his voice actor, Takashi Nagasako.',
    created_at: 'Sun Nov 07 2021 14:56:15 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/9.png',
  },
  {
    objectID: '2ea044f5-0749-4c9e-9d56-1cdb2472c805',
    name: 'Diddy Kong',
    universe: 'Donkey Kong',
    price: '331',
    popular: true,
    rate: 3,
    downloads: '15671',
    description:
      'Diddy Kong (ディディーコング, Diddy Kong) is a playable character in Super Smash Bros. Ultimate. He was officially confirmed on June 12th, 2018 alongside Olimar and the rest of the returning roster. Unlike his previous appearances in the Super Smash Bros. series, Diddy Kong is now an unlockable character instead of a starter character. Diddy Kong is classified as Fighter #36. Diddy Kong once again retains his realistic chimpanzee screeches that were used in both Brawl and Smash 4 instead of being voiced by Katsumi Suzuki.',
    created_at: 'Sat Dec 18 2021 18:03:01 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/10.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Link',
    universe: 'The Legend of Zelda',
    price: '70',
    popular: true,
    rate: 1,
    downloads: '50089',
    description:
      "Link (リンク, Link) is a playable character in Super Smash Bros. Ultimate. He was suggested to appear in the then unnamed Ultimate in its first teaser trailer at the end of the March 8th, 2018 Nintendo Direct, and officially announced in Ultimate's E3 2018 trailer on June 12th. Link is classified as Fighter #03. Kengo Takanashi, Link's voice actor from The Legend of Zelda: Breath of the Wild, reprises his role in Ultimate with newly recorded voice clips, replacing Akira Sasanuma's portrayal from The Legend of Zelda: Twilight Princess used in Brawl and SSB4.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/11.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Zelda',
    universe: 'The Legend of Zelda',
    price: '279',
    popular: true,
    rate: 1,
    downloads: '17311',
    description:
      "Zelda (ゼルダ, Zelda) is a playable character in Super Smash Bros. Ultimate. She was confirmed as a playable character along with Sheik and the rest of veterans on June 12, 2018. Unlike the game's predecessors, she is unlockable instead of being available from the start. Zelda is classified as Fighter #17. In a similar vein to her fellow Zelda fighters Link and Ganondorf, Zelda is now voiced by Ayumi Fujimura, who reprises her role from The Legend of Zelda: A Link Between Worlds, replacing Jun Mizusawa from Melee, Brawl, and Smash 4. Similar to Star Fox characters in Melee, the former provides a single line of spoken Japanese dialogue in World of Light's opening; this line is dubbed in English by Brandy Kopp, who also voices Palutena.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/12.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Sheik',
    universe: 'The Legend of Zelda',
    price: '623',
    popular: true,
    rate: 2,
    downloads: '42000',
    description:
      "Sheik (シーク, Sheik) is a playable character in Super Smash Bros. Ultimate. She was officially confirmed on June 12th, 2018 alongside Zelda and the rest of the returning roster. Sheik is classified as Fighter #16. As with Zelda, this is the first time in the series to not have Sheik voiced by Jun Mizusawa since Melee; as a result of Zelda's The Legend of Zelda: A Link Between Worlds-based recast, Ayumi Fujimura now also voices Sheik, continuing the trend from Mizusawa voicing both characters in the previous games.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/13.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Ganondorf',
    universe: 'The Legend of Zelda',
    price: '865',
    popular: true,
    rate: 1,
    downloads: '40154',
    description:
      'Ganondorf (ガノンドロフ, Ganondorf) is a playable character in Super Smash Bros. Ultimate. He was officially revealed alongside Ryu and the rest of the returning roster on June 12th, 2018 during E3 2018. Like in games prior to Super Smash Bros. for Wii U, he is unlockable, instead of being available from the start. Ganondorf is classified as Fighter #23. Takashi Nagasako reprises his role as Ganondorf after having previously voiced the character in The Legend of Zelda: Ocarina of Time, The Legend of Zelda: The Wind Waker and Super Smash Bros. Melee, providing new voice clips that sound more akin to the former game, replacing Hironori Miyata from Brawl and Smash 4.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/14.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Young Link',
    universe: 'The Legend of Zelda',
    price: '704',
    popular: true,
    rate: 1,
    downloads: '50969',
    description:
      "Young Link (こどもリンク, Young Link) is a playable character in Super Smash Bros. Ultimate. He was officially confirmed as playable alongside his former successor Toon Link on June 12th, 2018. Although the changes made to Link were not enough to change Young Link's status as a clone, he is not classified as an Echo Fighter. As such, Young Link is classified as Fighter #22. As in Super Smash Bros. Melee, Fujiko Takimoto's portrayals of Young Link from The Legend of Zelda: Ocarina of Time and Majora's Mask were repurposed for Ultimate, with mostly returning voice clips from Melee, and in addition to some new ones sourced from these games.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/15.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Toon Link',
    universe: 'The Legend of Zelda',
    price: '100',
    popular: true,
    rate: 5,
    downloads: '56396',
    description:
      "Toon Link (トゥーンリンク, Toon Link) is a playable character in Super Smash Bros. Ultimate. He was officially confirmed as playable alongside his predecessor Young Link and the rest of veterans on June 12th, 2018. As in Super Smash Bros. Brawl, he is unlockable, instead of being available from the start. Toon Link is classified as Fighter #43. As in Brawl and Super Smash Bros. 4, Sachi Matsumoto's portrayal of Toon Link from The Legend of Zelda: The Wind Waker was repurposed for Ultimate.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/16.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Samus',
    universe: 'Metroid',
    price: '604',
    popular: true,
    rate: 2,
    downloads: '6290',
    description:
      "Samus (サムス, Samus) is a playable character in Super Smash Bros. Ultimate. She was suggested to appear on the then-unnamed Ultimate's announcement trailer, and officially confirmed in the gameplay trailer on June 12, 2018 during E3 2018. Samus retains her modified Metroid: Other M design from Smash 4 and is classified as Fighter #04.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/17.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Zero Suit Samus',
    universe: 'Metroid',
    price: '841',
    popular: true,
    rate: 5,
    downloads: '45706',
    description:
      "Zero Suit Samus (ゼロスーツサムス, Zero Suit Samus) is a playable character in Super Smash Bros. Ultimate. She was officially revealed on June 12th, 2018 alongside Wii Fit Trainer and the rest of the returning roster. Once again, Zero Suit Samus is unconnected to the standard playable Samus, although she temporarily transforms into the latter during her Final Smash. Zero Suit Samus is classified as Fighter #29. As in Smash 4, Alésia Glidewell's portrayal of Zero Suit Samus from Brawl was repurposed for Ultimate.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/18.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Kirby',
    universe: 'Kirby',
    price: '762',
    popular: true,
    rate: 3,
    downloads: '63630',
    description:
      'Kirby (カービィ, Kirby) is a playable character in Super Smash Bros. Ultimate. Like all veterans, he was confirmed on June 12th, 2018. Kirby is classified as Fighter #06. Kirby is voiced in all regions once again by Makiko Ōmoto, using a combination of new voice clips and ones recycled from Super Smash Bros. 4.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/19.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Meta Knight ',
    universe: 'Kirby',
    price: '764',
    popular: true,
    rate: 3,
    downloads: '53398',
    description:
      "Meta Knight (メタナイト, Meta Knight) is a playable character in Super Smash Bros. Ultimate. He was officially confirmed on June 12th, 2018 during E3 2018, alongside Mewtwo and the rest of the returning roster. Meta Knight is classified as Fighter #27, the first fighter number of the Brawl veterans. As in Smash 4, Eric Newsome and Atsushi Kisaichi's portrayals from Brawl were repurposed for the English and Japanese versions of Ultimate, respectively.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/20.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'King Dedede',
    universe: 'Kirby',
    price: '627',
    popular: true,
    rate: 5,
    downloads: '45334',
    description:
      'King Dedede (デデデ, Dedede) is a playable character in Super Smash Bros. Ultimate. He was confirmed as playable along with Rosalina & Luma and the rest of the veterans on June 12th, 2018. King Dedede is classified as Fighter #39. King Dedede’s voice clips from Super Smash Bros. 4, where he was voiced by series creator Masahiro Sakurai, have been repurposed for Ultimate.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/21.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Fox',
    universe: 'Star Fox',
    price: '950',
    popular: true,
    rate: 4,
    downloads: '3441',
    description:
      'Fox (フォックス, Fox) is a playable fighter in Super Smash Bros. Ultimate. He was officially revealed on June 12th, 2018 alongside fellow Star Fox fighter Falco and the rest of the returning roster during the E3 2018 Nintendo Direct. Fox is classified as Fighter #07. Mike West reprises his role from Super Smash Bros. 4 with new voice clips, sounding more akin to his appearances in Star Fox Zero and Starlink: Battle for Atlas. In the Japanese version, Fox is now voiced by Takashi Ōhara, reprising his role from Star Fox 64 3D and Star Fox Zero, replacing Kenji Nojima from Brawl and Smash 4.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/22.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Falco',
    universe: 'Star Fox',
    price: '993',
    popular: true,
    rate: 2,
    downloads: '6003',
    description:
      'Falco (ファルコ, Falco) is a playable fighter in Super Smash Bros. Ultimate. He was officially revealed on June 12th, 2018 alongside fellow Star Fox fighter Fox and the rest of the returning roster during the E3 2018 Nintendo Direct. Falco is classified as Fighter #20. Mark Lund reprises his role from Super Smash Bros. 4 with new voice clips, sounding more akin to his appearances in Star Fox Zero and Starlink: Battle for Atlas. In the Japanese version, Falco is now voiced by Kōsuke Takaguchi, reprising his role from Star Fox 64 3D and Star Fox Zero and who also voiced Wolf, replacing Hisao Egawa from Melee, Brawl, and Smash 4.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/23.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Wolf',
    universe: 'Star Fox',
    price: '860',
    popular: true,
    rate: 1,
    downloads: '30246',
    description:
      'Wolf (ウルフ, Wolf) is a playable fighter in Super Smash Bros. Ultimate. He was officially revealed on June 12th, 2018 alongside the rest of the returning roster during the E3 2018 Nintendo Direct. Wolf is classified as Fighter #44, the last fighter number of the Brawl veterans. Jay Ward reprises his role from Super Smash Bros. Brawl with new voice clips, sounding more akin to his appearance in Starlink: Battle for Atlas. In the Japanese version, Wolf is now voiced by Kōsuke Takaguchi, reprising his role from Star Fox 64 3D and Star Fox Zero and who also voiced Falco, replacing Mahito Ōba from Brawl.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/24.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Pikachu',
    universe: 'Pokémon',
    price: '20',
    popular: true,
    rate: 1,
    downloads: '62531',
    description:
      "Pikachu (ピカチュウ, Pikachu) is a playable character in Super Smash Bros. Ultimate. It was confirmed on June 12th, 2018. Pikachu is classified as Fighter #08. As in Smash 4, Ikue Ōtani's portrayals of Pikachu from Melee and Brawl were repurposed for Ultimate.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/25.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Jigglypuff',
    universe: 'Pokémon',
    price: '616',
    popular: true,
    rate: 3,
    downloads: '64943',
    description:
      "Jigglypuff (プリン, Purin) is a playable character in Super Smash Bros. Ultimate. It was revealed alongside the fellow Pokémon fighter Pichu and the rest of veterans on June 12th, 2018. Like in games prior to Super Smash Bros. for Wii U, Jigglypuff is unlockable, instead of being available from the start. Jigglypuff is classified as Fighter #12, the last fighter number of the SSB veterans. As in Melee, Brawl, and Smash 4, Rachael Lillis' portrayal of Jigglypuff from Smash 64 was repurposed for the English version of Ultimate. Mika Kanai, Jigglypuff's voice actress from all previous Smash games and the Pokémon anime, reprises her role in the Japanese version, with new voice clips. Virginie Demians and Dina Kuerten's portrayals of Jigglypuff from Brawl were repurposed for the French and German versions.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/26.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Mewtwo',
    universe: 'Pokémon',
    price: '853',
    popular: true,
    rate: 5,
    downloads: '34237',
    description:
      "Mewtwo (ミュウツー, Mewtwo) is a playable character in Super Smash Bros. Ultimate. It was officially revealed on June 12th, 2018 alongside Meta Knight and the rest of the returning roster. Like in Melee, Mewtwo is once again an unlockable character. Mewtwo is classified as Fighter #24. Keiji Fujiwara's portrayal of Mewtwo from Smash 4 was repurposed for Ultimate. This is the last game for which Keiji Fujiwara voiced the character before he passed away in April 2020.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/27.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Pichu',
    universe: 'Pokémon',
    price: '850',
    popular: true,
    rate: 4,
    downloads: '61638',
    description:
      "Pichu (ピチュー, Pichu) is a playable character in Super Smash Bros. Ultimate. It was confirmed alongside Jigglypuff and the rest of the returning roster on June 12th, 2018 during E3 2018. While Pichu remains a full clone of Pikachu, it is not classified as an Echo Fighter. As such, Pichu is classified as Fighter #19. Satomi Kōrogi, Pichu's voice actress from the Pokémon anime and Melee, reprises her role with new voice clips. In addition, the 'spiky-eared' variant of Pichu (who appears as a playable character in Ultimate via Pichu's alternate costumes) is also voiced by Kōrogi rather than Shoko Nakagawa, who originally voiced the aforementioned 'spiky-eared' variant in the Pokémon anime's twelfth movie, Pokémon: Arceus and the Jewel of Life.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/28.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Pokémon Trainer',
    universe: 'Pokémon',
    price: '559',
    popular: true,
    rate: 1,
    downloads: '21192',
    description:
      'Pokémon Trainer (ポケモントレーナー, Pokémon Trainer) is a playable character in Super Smash Bros. Ultimate, confirmed on June 12th, 2018. Pokémon Trainer can use three interchangeable Pokémon in battle: Squirtle, Ivysaur, and Charizard. Pokémon Trainer, unlike most characters, was not given a fighter number; instead, the Pokémon are given numbers. Squirtle is classified as Fighter #33, Ivysaur is classified as Fighter #34, and Charizard is classified as Fighter #35. The male Pokémon Trainer has new voice clips in all languages he is voiced in.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/29.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Lucario',
    universe: 'Pokémon',
    price: '188',
    popular: true,
    rate: 4,
    downloads: '11515',
    description:
      'Lucario (ルカリオ, Lucario) is a playable character in Super Smash Bros. Ultimate. It was confirmed as a playable character on June 12th, 2018. As in Super Smash Bros. Brawl, Lucario is unlockable, instead of being available from the start. Lucario is classified as Fighter #41. Lucario is once again voiced in different languages provided by different voice actors, with their respective portrayals of Lucario from Super Smash Bros. 4 being repurposed for Ultimate.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/30.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Greninja',
    universe: 'Pokémon',
    price: '999',
    popular: true,
    rate: 2,
    downloads: '26218',
    description:
      "Greninja (ゲッコウガ, Gekkouga) is a playable character in Super Smash Bros. Ultimate. It was officially revealed on June 12th, 2018 alongside Mr. Game & Watch and the rest of the returning roster. Greninja is classified as Fighter #50. Billy Bob Thompson, Yūji Ueda, Frédéric Clou and Benedikt Gutjan's portrayals from Super Smash Bros. 4 were repurposed for the English, Japanese, French and German versions of Ultimate.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/31.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Captain Falcon',
    universe: 'F-Zero',
    price: '844',
    popular: true,
    rate: 1,
    downloads: '3595',
    description:
      "Captain Falcon (キャプテン・ファルコン, Captain Falcon) is a playable character in Super Smash Bros. Ultimate. He was confirmed on June 12th, 2018. As in the original Super Smash Bros. and Super Smash Bros. Brawl, he is unlockable, instead of being available from the start. Captain Falcon is classified as Fighter #11. As in Smash 4, Ryō Horikawa's portrayals of Captain Falcon from Melee and Brawl were repurposed for Ultimate. However, Horikawa briefly returned to voice Captain Falcon in Min Min's reveal trailer, though only recording eating sounds for Captain Falcon rather than new voice lines.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/32.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Ness',
    universe: 'EarthBound',
    price: '955',
    popular: true,
    rate: 4,
    downloads: '39270',
    description:
      'Ness (ネス, Ness) is a playable character in Super Smash Bros. Ultimate. He was revealed along with the fellow EarthBound fighter Lucas and all other previous veterans on June 12, 2018. As in the original Super Smash Bros., Super Smash Bros. Brawl, and Super Smash Bros. for Nintendo 3DS, he is unlockable, instead of being available from the start. Ness is classified as Fighter #10. In a first for the series, Makiko Ōmoto does not provide Ness with any new voice clips, with her portrayal of him from Super Smash Bros. 4 being repurposed for Ultimate.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/33.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Lucas',
    universe: 'EarthBound',
    price: '808',
    popular: true,
    rate: 1,
    downloads: '17096',
    description:
      "Lucas (リュカ, Lucas) is a playable character in Super Smash Bros. Ultimate. Lucas was revealed along with Ness and all other veterans on June 12th, 2018 and is classified as Fighter #37. As in Smash 4, Lani Minella's portrayal of Lucas from Brawl was repurposed for Ultimate.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/34.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Ice Climbers',
    universe: 'Ice Climbers',
    price: '423',
    popular: true,
    rate: 1,
    downloads: '29747',
    description:
      'The Ice Climbers (アイスクライマー, Ice Climber) are playable fighters in Super Smash Bros. Ultimate. They were confirmed on June 12th, 2018. Although they are a team, the Ice Climbers are collectively classified as Fighter #15. The Ice Climbers are once again voiced by Sanae Kobayashi, with her portrayals from Super Smash Bros. Melee and Super Smash Bros. Brawl being repurposed for Ultimate.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/35.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Martin',
    universe: 'Fire Emblem',
    price: '374',
    popular: true,
    rate: 3,
    downloads: '18942',
    description:
      'Marth (マルス, Marth) is a playable character in Super Smash Bros. Ultimate. Like all veterans, he was officially confirmed as a playable character on June 12th, 2018. As in his appearances prior to Super Smash Bros. 4, he is unlockable, instead of being available from the start. Marth is classified as Fighter #21. This is the first time in the Super Smash Bros. series where Marth is not solely voiced in Japanese. In international releases, Marth is voiced in English by Yuri Lowenthal, who reprises his role from Code Name: S.T.E.A.M. onwards. Hikaru Midorikawa reprises his role in the Japanese version, with new voice clips for the first time since Super Smash Bros. Brawl.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/36.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Roy',
    universe: 'Fire Emblem',
    price: '377',
    popular: true,
    rate: 5,
    downloads: '62539',
    description:
      "Roy (ロイ, Roy) is a playable character in Super Smash Bros. Ultimate, officially confirmed on June 12th, 2018 and is an unlockable fighter akin to his appearance in Melee. Roy is classified as Fighter #25. This is the first time in the Super Smash Bros. series where Roy is not voiced in Japanese in all regions. In international releases, Roy is voiced in English by Ray Chase, who reprises his role from Fire Emblem Heroes. Jun Fukuyama's portrayal of Roy from Smash 4 was repurposed for the Japanese version.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/37.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Ike',
    universe: 'Fire Emblem',
    price: '659',
    popular: true,
    rate: 1,
    downloads: '51691',
    description:
      'Ike (アイク, Ike) is a playable character in Super Smash Bros. Ultimate. He was officially confirmed on June 12th, 2018. Ike is classified as Fighter #32. Michihiko Hagi reprises his role in the Japanese version, now providing new voice clips, and Greg Chun now voices Ike in the English version, reprising his role from Fire Emblem Heroes and replacing Jason Adkins, who voiced him in Super Smash Bros. Brawl and Super Smash Bros. 4.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/38.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Robin',
    universe: 'Fire Emblem',
    price: '388',
    popular: true,
    rate: 5,
    downloads: '29744',
    description:
      "Robin (ルフレ, Reflet) is a playable character in Super Smash Bros. Ultimate. He was officially revealed on June 12th, 2018 alongside Lucina and the rest of the returning roster. As in the previous game, both male and female versions of Robin are playable, although the male Robin is showcased in promotional material and used as the default palette swap for the character. Robin is classified as Fighter #56. David Vincent and Lauren Landa's portrayals of both male and female Robin from Super Smash Bros. 4 were repurposed for Western editions of Ultimate. Additionally, Yoshimasa Hosoya and Miyuki Sawashiro's portrayals of both male and female Robin from SSB4 were repurposed for the Japanese editions of Ultimate, respectively.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/39.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Lucina',
    universe: 'Fire Emblem',
    price: '230',
    popular: true,
    rate: 2,
    downloads: '62440',
    description:
      "Lucina (ルキナ, Lucina) is a playable character in Super Smash Bros. Ultimate. She was officially revealed on June 12th, 2018 alongside Robin and the rest of the returning roster. Lucina is Marth's Echo Fighter, thus being classified as Fighter #21ε. Both Laura Bailey and Yū Kobayashi's respective English and Japanese portrayals of Lucina from Super Smash Bros. 4 were repurposed for, respectively, the western and Japanese versions of Ultimate. As a consequence of this, Lucina is not voiced by her current English voice actress, Alexis Tipton, who has otherwise held the role since 2017; she is one of only two Fire Emblem characters in Ultimate to not be portrayed by their current English actor from Fire Emblem Heroes onward, the other being Lyn.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/40.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Corrin',
    universe: 'Fire Emblem',
    price: '762',
    popular: true,
    rate: 3,
    downloads: '18158',
    description:
      "Corrin (カムイ, Kamui) is a playable character in Super Smash Bros. Ultimate that was officially confirmed on June 12th, 2018. As in Smash 4, both male and female versions of the character are playable. Corrin is classified as Fighter #62. Cam Clarke and Nobunaga Shimazaki's portrayals of male Corrin in English and Japanese and Marcella Lentz-Pope and Satomi Sato's portrayals of female Corrin in English and Japanese from Smash 4 were repurposed for Ultimate.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/41.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Mr. Game & Watch',
    universe: 'Game & Watch',
    price: '525',
    popular: true,
    rate: 3,
    downloads: '36604',
    description:
      'Mr. Game & Watch (Mr.ゲーム＆ウォッチ, Mr. Game & Watch) is a playable character in Super Smash Bros. Ultimate. He was confirmed alongside Greninja and the rest of the returning roster on June 12th, 2018 during E3 2018. Mr. Game & Watch is classified as Fighter #26, the last fighter number of the Melee veterans. As in his Smash 4 incarnation, Mr. Game & Watch reuses his sound effects from Melee and Brawl for Ultimate.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/42.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Pit',
    universe: 'Kid Icarus',
    price: '165',
    popular: true,
    rate: 2,
    downloads: '819898421',
    description:
      'Pit (ピット, Pit) is a playable character in Super Smash Bros. Ultimate. He was officially revealed on June 12th, 2018 alongside fellow Kid Icarus fighters Dark Pit and Palutena, and the rest of the returning roster. Pit is classified as Fighter #28. Antony Del Rio and Minami Takayama reprise their roles as Pit in the English and Japanese versions of the game, through recycled voice clips from Smash 4 along with some new ones. As in SSB4, the former still remains uncredited with his role, most likely because of him still being a union-based voice actor.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/43.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Palutena',
    universe: 'Kid Icarus',
    price: '507',
    popular: true,
    rate: 4,
    downloads: '53545',
    description:
      "Palutena (パルテナ, Palutena) is a playable character in Super Smash Bros. Ultimate. She was officially revealed on June 12th, 2018 alongside fellow Kid Icarus fighters Pit and Dark Pit, and the rest of the returning roster. Palutena is classified as Fighter #54. Brandy Kopp and Aya Hisakawa reprise their role as the voice of Palutena in the English and Japanese versions of the game; in addition to their portrayals being re-purposed from Super Smash Bros. 4, they also provide new Palutena's Guidance conversations for every veteran not present in Smash 4, DLC character in Smash 4, Ultimate base roster newcomer, and Piranha Plant.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/44.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Drk Pit',
    universe: 'Kid Icarus',
    price: '532',
    popular: true,
    rate: 5,
    downloads: '67814',
    description:
      "Dark Pit (ブラックピット, Black Pit) is a playable character in Super Smash Bros. Ultimate. He was officially revealed on June 12th, 2018 alongside fellow Kid Icarus fighters Pit and Palutena, and the rest of the returning roster. Dark Pit is Pit's Echo Fighter, thus being classified as Fighter #28ε. Antony Del Rio and Minami Takayama's portrayals of Dark Pit from SSB4 were repurposed for the English and Japanese versions of Ultimate, respectively, with the former once again remaining uncredited. However, they both provide new voice clips for certain Palutena's Guidance conversations.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/45.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Wario',
    universe: 'Wario',
    price: '475',
    popular: true,
    rate: 4,
    downloads: '60983',
    description:
      "Wario (ワリオ, Wario) is a playable character in Super Smash Bros. Ultimate. He was officially revealed on June 12th, 2018 alongside Little Mac and the rest of the returning roster. Wario is classified as Fighter #30. As in SSB4, Charles Martinet's portrayal of Wario from Brawl was repurposed for Ultimate.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/46.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Olimar',
    universe: 'Pikmin',
    price: '945',
    popular: true,
    rate: 4,
    downloads: '67494',
    description:
      "Olimar (ピクミン＆オリマー, Pikmin & Olimar) is a playable character in Super Smash Bros. Ultimate. He was officially revealed on June 12th, 2018 alongside Diddy Kong and the rest of the returning roster. In addition, Alph (ピクミン＆アルフ, Pikmin & Alph) returns as an alternate character alongside Olimar. Olimar is classified as Fighter #40. Olimar uses Pikmin to assist him in attacking his foes, with a core playstyle revolving around managing and using his various Pikmin combinations to his advantage. As in Brawl and Smash 4, Hajime Wakai's portrayals of the Pikmin from Pikmin and Pikmin 2, and Atsuko Asahi's portrayals of the Winged Pikmin from Pikmin 3 were repurposed for Ultimate.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/47.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'R.O.B.',
    universe: 'R.O.B.',
    price: '566',
    popular: true,
    rate: 5,
    downloads: '27936',
    description:
      "R.O.B. (ロボット, Robot) is a playable character in Super Smash Bros. Ultimate. He was officially revealed on June 12th, 2018 alongside Dr. Mario, Duck Hunt, and the rest of the returning roster. R.O.B. is classified as Fighter #42. R.O.B.'s beeping sound effects from Brawl and Smash 4 were repurposed for Ultimate.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/48.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Villager',
    universe: 'Animal Crossing',
    price: '442',
    popular: true,
    rate: 3,
    downloads: '47245',
    description:
      'Villager (むらびと, Murabito) is a playable character in Super Smash Bros. Ultimate, officially confirmed on June 12th, 2018. Villager is classified as Fighter #45, the first fighter number of the SSB4 veterans.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/49.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Little Mac',
    universe: 'Punch-Out!!',
    price: '456',
    popular: true,
    rate: 5,
    downloads: '29335',
    description:
      'Little Mac (リトル・マック, Little Mac) is a playable character in Super Smash Bros. Ultimate. He was officially revealed on June 12th, 2018 alongside Wario and the rest of the returning roster. Little Mac is classified as Fighter #49. Kōsuke Toriumi reprises his role as Little Mac in the game, albeit via reused voice clips from Smash 4.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/50.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Wii Fit Trainer ',
    universe: 'Wii Fit',
    price: '217',
    popular: true,
    rate: 1,
    downloads: '36746',
    description:
      "Wii Fit Trainer (Wii Fit トレーナー, Wii Fit Trainer) is a playable character in Super Smash Bros. Ultimate. She was officially revealed on June 12th, 2018 alongside Zero Suit Samus and the rest of the returning roster. Wii Fit Trainer is classified as Fighter #47. As in Smash 4, both the female and male versions of Wii Fit Trainer are playable. All of the voice actors' portrayals of the female and male Wii Fit Trainers from Smash 4 (Wii Fit series in Japanese) are repurposed for Ultimate.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/51.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Shulk',
    universe: 'Xenoblade Chronicles',
    price: '705',
    popular: true,
    rate: 2,
    downloads: '46990',
    description:
      "Shulk (シュルク, Shulk) is a playable character in Super Smash Bros. Ultimate. He was confirmed on June 12th, 2018. Shulk is classified as Fighter #57. Adam Howden and Shintarō Asanuma reprise their roles as Shulk's voice actors in the English and Japanese versions of the game through mostly recycled voice clips from Super Smash Bros. 4. Howden and Asanuma additionally reprised their roles for Pyra and Mythra's reveal trailer.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/52.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Duck Hunt',
    universe: 'Duck Hunt',
    price: '462',
    popular: true,
    rate: 5,
    downloads: '62581',
    description:
      'Duck Hunt (ダックハント, Duckhunt), known in PAL versions as Duck Hunt Duo, is a playable fighter in Super Smash Bros. Ultimate. They were officially revealed on June 12th, 2018 alongside Dr. Mario, R.O.B., and the rest of the returning roster. Although they are a team, Duck Hunt are collectively classified as Fighter #59. Duck Hunt retain their realistic dog barks and duck quacks, using a combination of recycled voice clips from SSB4 along with additional new ones.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/53.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Snake',
    universe: 'Metal Gear',
    price: '833',
    popular: true,
    rate: 2,
    downloads: '14392',
    description:
      "Snake (スネーク, Snake) is a playable character in Super Smash Bros. Ultimate. He was officially confirmed on June 12th, 2018, with his appearance exclaiming 'Everyone is Here!' with the rest of the returning roster. Snake is classified as Fighter #31. David Hayter and Akio Ōtsuka's portrayals of Snake from Brawl were repurposed for the English and Japanese version of Ultimate respecitvely, with the former initially confirming on Twitter that he would be reprising his role as Snake.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/54.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Sonic',
    universe: 'Sonic the Hedgehog',
    price: '208',
    popular: true,
    rate: 2,
    downloads: '32529',
    description:
      "Sonic (ソニック, Sonic) is a playable character in Super Smash Bros. Ultimate. He was confirmed as a playable character on June 12th, 2018. As in Super Smash Bros. Brawl, he is unlockable, instead of being available from the start. Sonic is classified as Fighter #38. As in Smash 4, Sonic's voice clips from the Japanese version of Brawl, the English version of Sonic Generations, Sonic & All-Stars Racing Transformed, and Mario & Sonic at the London 2012 Olympic Games, and the French, Spanish, German, Italian versions of Sonic Generations and Smash 4 were repurposed for Ultimate.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/55.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Mega Man',
    universe: 'Mega Man',
    price: '810',
    popular: true,
    rate: 2,
    downloads: '41889',
    description:
      'Mega Man (ロックマン, Rockman) is a playable character in Super Smash Bros. Ultimate, officially confirmed on June 12th, 2018. Mega Man is classified as Fighter #46.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/56.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Pac-Man',
    universe: 'Pac-Man',
    price: '670',
    popular: true,
    rate: 1,
    downloads: '6146',
    description:
      'Pac-Man (パックマン), stylized in-game as PAC-MAN, is a playable character in Super Smash Bros. Ultimate. He was confirmed on June 12, 2018. Pac-Man is classified as Fighter #55.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/57.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Ryu',
    universe: 'Street Fighter',
    price: '550',
    popular: true,
    rate: 4,
    downloads: '54940',
    description:
      'Ryu (リュウ, Ryū) is a playable character in Super Smash Bros. Ultimate. He is the second fighter from Capcom after Mega Man. He was officially confirmed alongside Ganondorf and the rest of the returning roster on June 12th, 2018 during E3 2018. Ryu is classified as Fighter #60. Ryu is once again voiced by Kyle Hebert in English and Hiroki Takahashi in Japanese, with their portrayals from Super Smash Bros. 4 being repurposed for the English and Japanese releases of Ultimate, respectively.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/58.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Cloud',
    universe: 'Final Fantasy',
    price: '130',
    popular: true,
    rate: 3,
    downloads: '61267',
    description:
      "Cloud (クラウド, Cloud) is a playable character in Super Smash Bros. Ultimate. Cloud was confirmed on June 12th, 2018 and is classified as Fighter #61. Takahiro Sakurai reprises his role as Cloud in all regions, albeit via recycled voice clips from Super Smash Bros. 4. This makes him the first character to remain fully voiced in Japanese in all regions despite having an existing English voice actor. In Sephiroth's reveal trailer, and as part of the version 10.1.0 update, Sakurai reprises his role as Cloud with new voice lines exclusively for the Advent Children costumes, albeit only for his aesthetically different Omnislash Ver. 5.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/59.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Bayonetta',
    universe: 'Bayonetta',
    price: '863',
    popular: true,
    rate: 4,
    downloads: '32009',
    description:
      'Bayonetta (ベヨネッタ, Bayonetta) is a playable character in Super Smash Bros. Ultimate, making her return from the previous game. She is the second fighter from Sega after Sonic. She was confirmed alongside the rest of the returning roster on June 12th, 2018 during E3 2018. Bayonetta is classified as Fighter #63, the last fighter number of the SSB4 veterans and returning veterans as a whole. Hellena Taylor and Atsuko Tanaka reprise their roles in English and Japanese respectively, albeit via recycled voice clips from Super Smash Bros. 4.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/60.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Mii Brawler',
    universe: 'Super Smash Bros',
    price: '140',
    popular: true,
    rate: 5,
    downloads: '65886',
    description:
      'The Mii Brawler (Mii格闘タイプ, Mii Hand-to-Hand Fighting Type) is a playable character in Super Smash Bros. Ultimate. They were confirmed as a playable character on June 12th, 2018 along with the other Mii Fighter types, the Swordfighter, and the Gunner. Mii Brawler is classified as Fighter #51. As with the other Mii Fighter types, the Mii Brawler has 12 voice options, provided by Yūji Kishi, Takashi Ōhara, Ryōtarō Okiayu, Michihiko Hagi, Hideo Ishikawa, Kiyoyuki Yanada, Umeka Shōji, Ayumi Fujimura, Makiko Ōmoto, Minami Takayama, and Kimiko Saitō.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/61.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Mii Swordfighter',
    universe: 'Super Smash Bros',
    price: '886',
    popular: true,
    rate: 2,
    downloads: '48936',
    description:
      'The Mii Swordfighter (Mii剣術タイプ, Mii Fencing Type) is a playable character in Super Smash Bros. Ultimate. They were confirmed as a playable character on June 12th, 2018, along with the other Mii Fighter types, Brawler and Gunner. Mii Swordfighter is classified as Fighter #52. As with the other Mii Fighters, they have 12 voice options, provided by Yūji Kishi, Takashi Ōhara, Ryōtarō Okiayu, Michihiko Hagi, Hideo Ishikawa, Kiyoyuki Yanada, Umeka Shōji, Ayumi Fujimura, Makiko Ōmoto, Minami Takayama, and Kimiko Saitō.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/62.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Mii Gunner',
    universe: 'Super Smash Bros',
    price: '598',
    popular: true,
    rate: 4,
    downloads: '49524',
    description:
      'The Mii Gunner (Mii射撃タイプ, Mii Shooting Type) is a playable character in Super Smash Bros. Ultimate. They were confirmed as a playable character on June 12th, 2018, along with the other Mii Fighter types, Brawler and Swordfighter. Mii Gunner is classified as Fighter #53. As with the other Mii Fighters, the Miis have 12 voice options, provided by Yūji Kishi, Takashi Ōhara, Ryōtarō Okiayu, Michihiko Hagi, Hideo Ishikawa, Kiyoyuki Yanada, Umeka Shōji, Ayumi Fujimura, Makiko Ōmoto, Minami Takayama, and Kimiko Saitō.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/63.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Daisy',
    universe: 'Mario',
    price: '769',
    popular: true,
    rate: 3,
    downloads: '34571',
    description:
      "Daisy (デイジー, Daisy) is a playable character in Super Smash Bros. Ultimate. She was revealed as a newcomer alongside Inkling and Ridley on June 12th, 2018. Daisy is Peach's Echo Fighter and was the first new Echo Fighter to be revealed, thus being classified as Fighter #13ε. Deanna Mustard, Daisy's voice actress since Mario Golf: Toadstool Tour, reprises her role in all regions, albeit via repurposed voice clips from Mario Kart Wii, Mario Super Sluggers, Mario Party 9, Mario Kart 8, Mario Party 10, Mario & Sonic at the Rio 2016 Olympic Games and Super Mario Run.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/64.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Piranha Plant',
    universe: 'Mario',
    price: '738',
    popular: true,
    rate: 3,
    downloads: '17459',
    description:
      'Piranha Plant (パックンフラワー, Packun Flower) is a playable character in Super Smash Bros. Ultimate. Revealed alongside Ken and Incineroar on November 1st, 2018, it is the first DLC character in Ultimate, and was made available for purchase on February 1st, 2019. However, it was made available at no cost as early as January 29th, 2019 for players who purchased the digital version of Ultimate or registered their physical version with My Nintendo by January 31st, 2019. Piranha Plant is not part of either Fighters Pass, making it the only DLC character with this distinction. Piranha Plant is classified as Fighter #70.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/65.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'King K. Rool',
    universe: 'Donkey Kong',
    price: '958',
    popular: true,
    rate: 2,
    downloads: '37688',
    description:
      'King K. Rool (キングクルール, King K. Rool) is a playable character in Super Smash Bros. Ultimate. He was announced as a newcomer during the August 8th, 2018 Super Smash Bros. Ultimate Direct alongside Simon, Richter, Chrom, and Dark Samus. King K. Rool is classified as Fighter #67. Rather than being voiced by Toshihide Tsuchiya, who voiced the character since the 2007 title Donkey Kong Barrel Blast and the 2008 title Mario Super Sluggers, both games for the Wii, King K. Rool has a set of realistic crocodile roars and bellows, similar to how Bowser, Donkey Kong, and Diddy Kong emit realistic animal sounds as opposed to having dedicated voice acting.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/66.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Ridley',
    universe: 'Metroid',
    price: '954',
    popular: true,
    rate: 5,
    downloads: '46143',
    description:
      "Ridley (リドリー, Ridley) is a playable character in Super Smash Bros. Ultimate. He was revealed as a newcomer alongside Inkling and Daisy from Nintendo's 2018 E3 press conference, on June 12th, 2018, with an animated trailer. Ridley is classified as Fighter #65. Similar to Bowser, Donkey Kong, Diddy Kong, and King K. Rool, Ridley has no voice actor and instead uses computer-generated, more realistic roars and screeches, akin to his sounds in Super Smash Bros. Brawl, Super Smash Bros. for Wii U, and all of his appearances in the Metroid series.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/67.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Dark Samus',
    universe: 'Metroid',
    price: '424',
    popular: true,
    rate: 1,
    downloads: '24099',
    description:
      "Dark Samus (ダークサムス, Dark Samus) is a playable character in Super Smash Bros. Ultimate. She was announced as a newcomer during the August 8th, 2018 Super Smash Bros. Direct alongside Simon, Richter, Chrom, and King K. Rool. Dark Samus is Samus's Echo Fighter, thus being classified as Fighter #04ε. The sound effects used for Samus in Brawl and Smash 4 were repurposed for Dark Samus in Ultimate.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/68.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Incineroar',
    universe: 'Pokémon',
    price: '567',
    popular: true,
    rate: 4,
    downloads: '34269',
    description:
      "Incineroar (ガオガエン, Gaogaen) is a playable character in Super Smash Bros. Ultimate. It was confirmed as a playable character alongside Ken and Piranha Plant on November 1st, 2018, and was the final newcomer revealed for the base roster. Incineroar is classified as Fighter #69. Tyler Bunch (credited as 'H.D. Quinn'), who voiced Ash's Incineroar and Professor Kukui's Incineroar in the Sun and Moon anime, reprises his role as the Pokémon in English. In Japanese, it is voiced by Unshō Ishizuka, who passed away 2 months and 19 days before Incineroar's reveal. Incineroar also has different voice actors for the French and German versions due to its name being different in those languages, being voiced by Frédéric Clou in French and an unidentified voice actor in German.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/69.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Chrom',
    universe: 'Fire Emblem',
    price: '272',
    popular: true,
    rate: 2,
    downloads: '11602',
    description:
      "Chrom (クロム, Chrom) is a playable character in Super Smash Bros. Ultimate. He was announced as a newcomer alongside Simon, Richter, Dark Samus, and King K. Rool in the Nintendo Direct on August 8th, 2018. Chrom is Roy's Echo Fighter, thus being classified as Fighter #25ε, though his lack of sweetspots makes him parallel Roy the same way Lucina parallels Marth. In addition to his role as a playable character, Chrom remains a part of Robin's final smash Pair Up. Matthew Mercer and Tomokazu Sugita, who voiced Chrom in the English and Japanese versions of Fire Emblem Awakening respectively, reprise their roles in the international and Japanese versions of Ultimate. Both voice actors initially revealed their roles on their Twitter accounts [1] [2].",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/70.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Byleth',
    universe: 'Fire Emblem',
    price: '894',
    popular: true,
    rate: 3,
    downloads: '22913',
    description:
      'Byleth (♂: ベレト,[1] ♀: ベレス,[1] Byleth) is a playable character in Super Smash Bros. Ultimate. Byleth was officially announced on January 16th, 2020 as the fifth and final downloadable character from Fighters Pass Vol. 1. Both male and female versions of Byleth are playable. Byleth was released as part of Challenger Pack 5 on January 28th, 2020 and is classified as Fighter #75. Zach Aguilar and Jeannie Tirado, who respectively voiced the male and female versions of Byleth in Fire Emblem: Three Houses and Fire Emblem Heroes, reprise their roles in the overseas version, while Yūsuke Kobayashi and Shizuka Itō reprise their respective male and female roles in the Japanese version.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/71.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Isabelle',
    universe: 'Animal Crossing',
    price: '46',
    popular: true,
    rate: 1,
    downloads: '26178',
    description:
      'Isabelle (しずえ, Shizue) is a playable character in Super Smash Bros. Ultimate. She was announced as a newcomer at the end of the September 13, 2018 Nintendo Direct in tandem with the then-untitled Animal Crossing: New Horizons. While she shares many moves with Villager, Isabelle is not classified as an Echo Fighter, and is instead a semi-clone. As such, Isabelle is classified as Fighter #68. Although Isabelle speaks Animalese within her home series and reveal trailer, she is completely mute in Ultimate.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/72.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Mythra',
    universe: 'Xenoblade Chronicles',
    price: '547',
    popular: true,
    rate: 5,
    downloads: '30563',
    description:
      "Mythra (ヒカリ, Hikari) is a playable character in Super Smash Bros. Ultimate. She was confirmed as a playable character alongside Pyra during the February 17th, 2021 Nintendo Direct, and were released as part of Challenger Pack 9 on March 4th, 2021 in Fighters Pass Vol. 2. While her moveset is similar to Pyra's (aside from three of her Special moves and Final Smash), she is not classified as an Echo Fighter, and is instead a transformation semi-clone of Pyra. As such, Mythra is classified as Fighter #80. While Pyra is the selectable character by default across all palettes, the player can choose to start as Mythra by clicking on her in their fighter portrait at the character selection screen, in the same manner as one chooses which Pokémon to start with when choosing Pokémon Trainer. In all regions, Skye Bennett reprises her role as Mythra in English and Shino Shimoji reprises her role in Japanese, both with all new voice clips.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/73.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Inkling',
    universe: 'Splatoon',
    price: '69',
    popular: true,
    rate: 5,
    downloads: '59790',
    description:
      "Inkling (インクリング, Inkling) is a playable character in Super Smash Bros. Ultimate. Although the default costume is female, both male and female versions of this character are playable. They were the first characters that were suggested to appear in the then-unnamed Ultimate in its first teaser trailer at the end of the March 8th, 2018 Nintendo Direct, and officially announced as a newcomer in Ultimate's E3 2018 trailer, alongside Daisy and Ridley. Inkling is classified as Fighter #64, the first fighter number of the newcomers. Yuki Tsuji reprises his role as both genders of Inkling in all regions, albeit via recycled voice clips from Splatoon and Splatoon 2.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/74.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Min Min',
    universe: 'ARMS',
    price: '801',
    popular: true,
    rate: 1,
    downloads: '20294',
    description:
      'Min Min (ミェンミェン, MinMin) is a playable character in Super Smash Bros. Ultimate. She is the seventh downloadable character in Ultimate and the first downloadable character in Fighters Pass Vol. 2. An ARMS character was announced to be playable as part of Challenger Pack 6 on March 26th, 2020 during a Nintendo Direct Mini. However, it was not revealed that it would be Min Min until June 22nd, 2020 during a Mr. Sakurai Presents. Min Min was released as part of Challenger Pack 6 on June 29th, 2020 (June 30th, 2020 in Europe and Asia), and is classified as Fighter #76. Haruna Takatsu reprises her role as Min Min, with her portrayal from ARMS being re-purposed for Ultimate in all regions.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/75.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Ken',
    universe: 'Street Fighter',
    price: '975',
    popular: true,
    rate: 4,
    downloads: '8869',
    description:
      "Ken (ケン, Ken) is a playable character in Super Smash Bros. Ultimate. He is the third fighter from Capcom after Mega Man and Ryu. He was announced as a newcomer during the November 1st, 2018 Super Smash Bros. Ultimate Direct, alongside Incineroar and Piranha Plant. Ken is Ryu's Echo Fighter and was the final Echo Fighter to be revealed, thus being classified as Fighter #60ε. Reuben Langdon, Ken’s English voice actor since Street Fighter IV, reprises his role in the overseas versions. His Japanese voice actor since Street Fighter III: Third Strike, Yuji Kishi, reprises his role in the Japanese version.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/76.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Sephiroth',
    universe: 'Final Fantasy',
    price: '68',
    popular: true,
    rate: 3,
    downloads: '24979',
    description:
      'Sephiroth (セフィロス, Sephiroth) is a playable character in Super Smash Bros. Ultimate, and the third fighter from Square Enix after Cloud and Hero. He was confirmed as a playable character on December 10th, 2020 at The Game Awards 2020, and was released as part of Challenger Pack 8 on December 22nd, 2020 as the third downloadable character from Fighters Pass Vol. 2. However, he could also become playable as early as December 17th, 2020 by defeating him in the limited-time Sephiroth Challenge that was made available from December 17th-22nd.[1] Sephiroth is classified as Fighter #78. Toshiyuki Morikawa, who has voiced Sephiroth since Final Fantasy VII: Advent Children, reprises his role as the character in all regions.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/77.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Simon',
    universe: 'Castlevania',
    price: '296',
    popular: true,
    rate: 2,
    downloads: '41327',
    description:
      "Simon (シモン, Simon) is a playable character in Super Smash Bros. Ultimate. He is the second fighter from Konami after Snake. He was announced as a newcomer during the August 8th, 2018 Super Smash Bros. Direct alongside Richter, Chrom, Dark Samus, and King K. Rool. Simon is classified as Fighter #66. Keith Silverstein, Simon's English voice actor in Castlevania: Judgment reprises his role as Simon in English versions of the game. Hideo Ishikawa, who voiced Simon in DreamMix TV World Fighters, also reprises the role in the Japanese version.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/78.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Richter',
    universe: 'Castlevania',
    price: '499',
    popular: true,
    rate: 2,
    downloads: '8249',
    description:
      "Richter (リヒター, Richter) is a playable character in Super Smash Bros. Ultimate. He is the third fighter from Konami after Snake and Simon. He was announced as a newcomer alongside Simon, Chrom, Dark Samus, and King K. Rool during a Nintendo Direct on August 8th, 2018. Richter and Simon take inspiration from each other's home series appearances, with Richter being classified as the Echo Fighter of the two, thus being classified as Fighter #66ε. Richter is voiced in English by David Vincent, his recurring voice actor from Castlevania: Dracula X Chronicles onward, who initially confirmed on Twitter. He is voiced in Japanese by Kiyoyuki Yanada, his voice actor from Symphony of the Night onward.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/79.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Joker',
    universe: 'Persona',
    price: '900',
    popular: true,
    rate: 2,
    downloads: '39391',
    description:
      "Joker (ジョーカー, Joker) is a playable character in Super Smash Bros. Ultimate. He is the third fighter from Sega after Sonic and Bayonetta. He was officially announced at The Game Awards 2018 on December 6th, 2018 as the first downloadable character from Fighters Pass Vol. 1. Joker was released as part of Challenger Pack 1 on April 17th, 2019 and is classified as Fighter #71. Xander Mobus, who voiced Joker in Persona 5 in English as well as the announcer, Master Hand, and Crazy Hand in Ultimate, reprises his role as the character in the English version of the game, while Jun Fukuyama, who previously voiced the character in Japanese and also voices Roy, reprises his role in Japanese. Despite Arsène being voiced by the same respective voice actors in Joker's initial reveal trailer, he remains completely silent during gameplay.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/80.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Hero',
    universe: 'Dragon Quest',
    price: '326',
    popular: true,
    rate: 4,
    downloads: '28747',
    description:
      "Hero (勇者, Hero) is a playable character in Super Smash Bros. Ultimate and the second fighter from Square Enix after Cloud. He was announced during the E3 Nintendo Direct alongside Banjo & Kazooie on June 11th, 2019 as the second downloadable character from Fighters Pass Vol. 1. The default Hero is the Luminary[1] from Dragon Quest XI, while Erdrick[2] from Dragon Quest III, Solo from Dragon Quest IV and Eight from Dragon Quest VIII also appear as alternate characters like the Koopalings and Alph. Unlike the Koopalings and Alph, however, they are all listed simply as 'Hero'. Hero was released as part of Challenger Pack 2 on July 30th, 2019 and is classified as Fighter #72. Mitsuki Saiga reprises her role as the Luminary from the Japanese version of Dragon Quest XI S, voicing him in all regions in place of his English voice actor, Rasmus Hardiker. Nobuyuki Hiyama, Takeshi Kusao and Yūki Kaji also debut as the voices of Erdrick, Solo and Eight, respectively, in all versions of the game.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/81.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Banjo & Kazooie',
    universe: 'Banjo-Kazooie',
    price: '760',
    popular: true,
    rate: 4,
    downloads: '39812',
    description:
      'Banjo & Kazooie (バンジョー&カズーイ, Banjo & Kazooie), formatted in their reveal trailer as Banjo-Kazooie, are a playable fighter in Super Smash Bros. Ultimate, and are the first third-party fighter from Microsoft. They were revealed alongside Hero during the E3 Nintendo Direct on June 11th, 2019 as the third downloadable fighter from Fighters Pass Vol. 1. Banjo & Kazooie were released as part of Challenger Pack 3 on September 4th, 2019 and are classified as Fighter #73. Chris Sutherland reprises his role as both Banjo & Kazooie, with his portrayals from across the Banjo-Kazooie series being repurposed for Ultimate in all regions.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/82.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Terry',
    universe: 'Fatal Fury',
    price: '27',
    popular: true,
    rate: 5,
    downloads: '35559',
    description:
      'Terry (テリー, Terry) is a playable character in Super Smash Bros. Ultimate and the first third-party fighter from SNK. He was officially announced in the September 4th, 2019 Nintendo Direct as the fourth downloadable character from Fighters Pass Vol. 1. Terry was released as part of Challenger Pack 4 on November 6th, 2019 and is classified as Fighter #74. Takashi Kondō, who has voiced Terry in The King of Fighters XIV onwards, reprises his role as the character in all regions.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/83.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Steve',
    universe: 'Minecraft',
    price: '630',
    popular: true,
    rate: 4,
    downloads: '55857',
    description:
      'Steve (スティーブ, Steve) is a playable character in Super Smash Bros. Ultimate, the second fighter from Microsoft after Banjo & Kazooie, and the eighth DLC character for Ultimate. He was confirmed as a playable character on October 1st, 2020 as the second downloadable character from Fighters Pass Vol. 2. Alex (アレックス, Alex), a Zombie (ゾンビ, Zombie), and an Enderman (エンダーマン, Enderman) also appear as alternate costumes. Steve was released as part of Challenger Pack 7 on October 13th, 2020 and is classified as Fighter #77.',
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/84.png',
  },
  {
    objectID: 'f56aa7cd-6c66-4752-bbb7-36fee86bd27d',
    name: 'Kazuya',
    universe: 'Tekken',
    price: '714',
    popular: true,
    rate: 4,
    downloads: '7884',
    description:
      "Kazuya (カズヤ, Kazuya) is a playable character in Super Smash Bros. Ultimate. He was officially announced at the E3 Nintendo Direct on June 15th, 2021 as the fifth downloadable character from Fighters Pass Vol. 2 and was released on June 29th, 2021 (June 30th, 2021 in Europe and Asia) as part of Challenger Pack 10. Kazuya is the second playable character from Bandai Namco after Pac-Man and is classified as Fighter #81. Masanori Shinohara, Kazuya's voice actor since Tekken 4, reprises his role in Ultimate in all regions.",
    created_at: 'Sat Jan 29 2022 01:50:52 GMT-0500 (-05)',
    imageURL: 'https://myapp.koombea.com/smash/85.png',
  },
];
